# Generated by Django 4.1.1 on 2022-10-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=50)),
            ],
        ),
    ]
