# Generated by Django 4.1.1 on 2022-10-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('banner_type', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('rarity', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
